[tool.black]
line-length = 88
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/(
  (
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pylint]
[tool.pylint.messages_control]
# Not picked-up currently, see pre-commit for now
disable="missing-module-docstring"
enable="bad-whitespace,bad-indentation,line-too-long"
